secrets:
  db_password:
    file: ./sec/db_password

services:
  homelab:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./tmp:/app/tmp
      - /mnt:/mnt
    environment:
      - HOMELAB_DB_HOST=db
      - HOMELAB_DB_PORT=5432
      - HOMELAB_DB_USER=homelab
      - HOMELAB_DB_PASSWORD=homelab
      - HOMELAB_DB_NAME=homelab
      - HOMELAB_DB_SSLMODE=disable
      - HOMELAB_DB_SSLCERT=
      - HOMELAB_DB_SSLKEY=
      - HOMELAB_DB_SSLCA=
      - HOMELAB_DB_SSLHOST=
      - HOMELAB_LOG_LEVEL=debug
      - HOMELAB_LOG_FORMAT=text
      - HOMELAB_LOG_TIMEZONE=UTC
      - HOMELAB_LOG_OUTPUT=stderr
    secrets:
      - db_password
    depends_on:
      - db
    develop:
      watch:
        - path: .
          action: rebuild
          ignore:
            - tmp/
            - .git/
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=homelab
      - POSTGRES_PASSWORD=homelab
      - POSTGRES_DB=homelab
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

