// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Photo struct {
	ID          int32
	Title       string
	Description string
	Path        string
	UploadDate  time.Time
	UploadUser  sql.NullInt32
	Category    sql.NullString
}

type Song struct {
	ID          int32
	Title       string
	Description string
	Path        string
	UploadDate  time.Time
	UploadUser  sql.NullInt32
	Category    sql.NullString
}

type User struct {
	ID       int32
	Username string
	Password []byte
}

type Video struct {
	ID          int32
	Title       string
	Description string
	Path        string
	UploadDate  time.Time
	UploadUser  sql.NullInt32
	Category    sql.NullString
}
