// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getPhotoById = `-- name: GetPhotoById :one
SELECT id, title, description, path, upload_date, upload_user, category
FROM photos
WHERE id = $1
`

func (q *Queries) GetPhotoById(ctx context.Context, id int32) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhotoById, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Path,
		&i.UploadDate,
		&i.UploadUser,
		&i.Category,
	)
	return i, err
}

const getPhotos = `-- name: GetPhotos :many
SELECT id, title, description, path, upload_date, upload_user, category
FROM photos
LIMIT $1
`

func (q *Queries) GetPhotos(ctx context.Context, limit int32) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, getPhotos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Path,
			&i.UploadDate,
			&i.UploadUser,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotosFromId = `-- name: GetPhotosFromId :many
SELECT id, title, description, path, upload_date, upload_user, category
FROM photos
WHERE id >= $2
LIMIT $1
`

type GetPhotosFromIdParams struct {
	Limit int32
	ID    int32
}

func (q *Queries) GetPhotosFromId(ctx context.Context, arg GetPhotosFromIdParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, getPhotosFromId, arg.Limit, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Path,
			&i.UploadDate,
			&i.UploadUser,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongById = `-- name: GetSongById :one
SELECT id, title, description, path, upload_date, upload_user, category
FROM songs
WHERE id = $1
`

func (q *Queries) GetSongById(ctx context.Context, id int32) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongById, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Path,
		&i.UploadDate,
		&i.UploadUser,
		&i.Category,
	)
	return i, err
}

const getSongs = `-- name: GetSongs :many
SELECT id, title, description, path, upload_date, upload_user, category
FROM songs
LIMIT $1
`

func (q *Queries) GetSongs(ctx context.Context, limit int32) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getSongs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Path,
			&i.UploadDate,
			&i.UploadUser,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsFromId = `-- name: GetSongsFromId :many
SELECT id, title, description, path, upload_date, upload_user, category
FROM songs
WHERE id >= $2
LIMIT $1
`

type GetSongsFromIdParams struct {
	Limit int32
	ID    int32
}

func (q *Queries) GetSongsFromId(ctx context.Context, arg GetSongsFromIdParams) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getSongsFromId, arg.Limit, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Path,
			&i.UploadDate,
			&i.UploadUser,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoById = `-- name: GetVideoById :one
SELECT id, title, description, path, upload_date, upload_user, category
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideoById(ctx context.Context, id int32) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoById, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Path,
		&i.UploadDate,
		&i.UploadUser,
		&i.Category,
	)
	return i, err
}

const getVideos = `-- name: GetVideos :many
SELECT id, title, description, path, upload_date, upload_user, category
FROM videos
LIMIT $1
`

func (q *Queries) GetVideos(ctx context.Context, limit int32) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Path,
			&i.UploadDate,
			&i.UploadUser,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosFromId = `-- name: GetVideosFromId :many
SELECT id, title, description, path, upload_date, upload_user, category
FROM videos
WHERE id >= $2
LIMIT $1
`

type GetVideosFromIdParams struct {
	Limit int32
	ID    int32
}

func (q *Queries) GetVideosFromId(ctx context.Context, arg GetVideosFromIdParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideosFromId, arg.Limit, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Path,
			&i.UploadDate,
			&i.UploadUser,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
